name: Cancel
on:
  workflow_run:
    workflows: ["Ensure PR"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.10.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
