name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  deploy:
    name: Deploy Site
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/*]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Enable webpack persistent caching
        uses: ./.github/actions/webpack-persistent-cache

      - run: npm ci
      - name: Build site
        run: npm run build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OPENCOLLECTIVE_API_KEY: ${{secrets.OPENCOLLECTIVE_API_KEY}}
      - run: npm run lint:links

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          clean: true
